jobs:
  clirr:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: .kokoro/install_dependencies.sh
    - continue-on-error: true
      env:
        JOB_TYPE: clirr
      run: .kokoro/build.sh
  dependencies:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: .kokoro/install_dependencies.sh
    - continue-on-error: true
      run: .kokoro/dependencies.sh
    strategy:
      matrix:
        java:
        - 8
        - 11
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: .kokoro/install_dependencies.sh
    - continue-on-error: true
      env:
        JOB_TYPE: lint
      run: .kokoro/build.sh
  units:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: .kokoro/install_dependencies.sh
    - continue-on-error: true
      env:
        JOB_TYPE: test
      run: .kokoro/build.sh
    - continue-on-error: true
      env:
        GOOGLE_CLOUD_UNIVERSE_DOMAIN: random.com
      name: Env Var Tests
      run: 'mvn test -B -ntp -Dclirr.skip=true -Denforcer.skip=true -PenvVarTest

        '
    strategy:
      matrix:
        java:
        - 8
        - 11
  units-java21:
    name: units (21)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Set jvm system property environment variable for surefire plugin (unit
        tests)
      run: echo "SUREFIRE_JVM_OPT=-Djvm=${JAVA_HOME}/bin/java" >> $GITHUB_ENV
      shell: bash
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      run: .kokoro/install_dependencies.sh
    - continue-on-error: true
      env:
        JOB_TYPE: test
      run: .kokoro/build.sh
  windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: git configuration to avoid automatic CRLF conversion
      run: 'git config --global core.autocrlf false

        git config --global core.eol lf

        '
    - continue-on-error: true
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      name: Install google-play-services artifact
      run: "mkdir play-services\ncd play-services\ncurl --output play-services-basement-8.3.0.aar\
        \ https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-basement/8.3.0/play-services-basement-8.3.0.aar\n\
        unzip play-services-basement-8.3.0.aar\nmvn install:install-file \\\n    -Dfile=classes.jar\
        \ \\\n    -DgroupId=com.google.android.google-play-services \\\n    -DartifactId=google-play-services\
        \ \\\n    -Dversion=1 \\\n    -Dpackaging=jar\n"
      shell: bash
    - continue-on-error: true
      env:
        JOB_TYPE: test
      run: .kokoro/build.sh
      shell: bash
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
